---
title: "Home Prices"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## setup

```{r cars}
library(tidyverse)
library(forecast)
library(lubridate)
library(recipes)
library(corrplot)
library(scales)
library(ranger)
library(randomForest)
library(purrr)
library(knitr)
library(randomForestSRC)
library(caret)
library(rsample)
library(ggthemes)
library(tidymodels)

train <- read.csv("C:/Users/asbru/Documents/Emory/Forecasting and Predictive Analytics/Final/house-prices-advanced-regression-techniques/train.csv", stringsAsFactors = FALSE)

test <- read.csv("C:/Users/asbru/Documents/Emory/Forecasting and Predictive Analytics/Final/house-prices-advanced-regression-techniques/train.csv", stringsAsFactors = FALSE)

fullset <- 
  train %>% 
  bind_rows(test) %>% 
  rowid_to_column("ID") %>% 
  select(-Id) %>% 
  rename(Id = ID)  



```

##Cleanup

```{r}
#Find NA Values
# navalues <- as.data.frame(map_df(fullset, function(x) sum(is.na(x)))) 
# 
# #View Columns with NA Values
# NATable <-
#   navalues %>% 
#   pivot_longer(colnames(navalues), names_to = "ColName", values_to = "NA_Count") %>% 
#   filter(NA_Count > 0)
# NATable %>% 
#   kable()

#Replace NA values for "None" for variables where NA actually means the house does not have the trait
fullset <- 
  fullset %>% 
  mutate_at(vars(Alley,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinType2,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PoolQC,Fence,MasVnrType,MiscFeature), ~replace(., is.na(.), "None")) %>% 
  mutate_at(vars(MasVnrArea), ~replace(MasVnrArea,is.na(.),0)) %>% 
  mutate_at(vars(MasVnrArea),as.numeric) %>% 
  mutate_at(vars(OverallQual,OverallCond),as.factor) %>% 
  mutate_if(is.character,as.factor)

  
```


#Recipe for model pre-processing

```{r}


fullsetv2 <-
  fullset %>% 
  mutate(porchtype = case_when(WoodDeckSF > 0 ~ "wooddeck",
                               OpenPorchSF > 0 ~ "openporch",
                               EnclosedPorch > 0 ~ "enclosed",
                               "3SsnPorch" > 0 ~ "threeseason",
                               ScreenPorch > 0 ~ "screen"),
         finishedbsmtsqft = TotalBsmtSF - BsmtUnfSF,
         totalfullbaths = FullBath + BsmtFullBath) %>% 
  select(Id,
         SalePrice,
         porchtype,
         PavedDrive,
         PoolArea,
         KitchenQual,
         MSZoning,
         LotArea,
         RoofStyle,
         RoofMatl,
         TotalBsmtSF,
         finishedbsmtsqft,
         BsmtFinType1,
         BedroomAbvGr,
         totalfullbaths,
         Fireplaces,
         FireplaceQu,
         SaleCondition,
         # Neighborhood,
         MSSubClass,
         # Utilities,
         OverallQual,
         # OverallCond,
         ExterQual,
         ExterCond,
         HeatingQC,
         CentralAir,
         HouseStyle,
         BldgType,
         GarageCars,
         HouseStyle,
         BldgType,
         GarageCars
      
         ) %>% 
  mutate_if(is.character,as.factor)




recipe2 <- recipe(SalePrice ~ ., data = fullsetv2) 

recipe2steps <-
  recipe2 %>% 
  step_dummy(all_nominal()) 

preppedrecipe2 <- prep(recipe2steps, training = fullsetv2, strings_as_factors = TRUE)

fullsetbaked <-
  bake(preppedrecipe2,fullsetv2)

#Split into train and test set 70/30 train/test to be used in linear regression model

set.seed(1)

splitdata <- 
  fullsetv2 %>% 
  initial_split(prop = 0.7)

trainv2 <-
  training(splitdata) %>% 
  mutate_if(is.factor,as.factor)
testv2 <-
  testing(splitdata) %>% 
  mutate_if(is.factor,as.factor)

# navalues <- as.data.frame(map_df(fullsetv2, function(x) sum(is.na(x)))) 
```


##EDA

```{r}
Saleshist<-
  trainv2 %>% 
  ggplot(aes(x = SalePrice, fill = Neighborhood)) +
  geom_histogram() +
  scale_x_continuous(labels = comma) +
  facet_wrap(~Neighborhood)
Saleshist

bldgtypebox <-
  trainv2 %>% 
  ggplot(aes(x = BldgType, y = SalePrice)) +
  geom_boxplot()

bldgtypebox

bsmttypebox <-
  trainv2 %>% 
  ggplot(aes(x = BldgType, y = SalePrice)) +
  geom_boxplot()


correlation <-
  trainbaked1 
 
M <- 
  cor(correlation)
# png(file="corr.png", res=300, width=4500, height=4500)
corrplot(M, method = "shade", number.cex = 1, tl.cex = 0.7, title = "Home Prices", mar=c(0,0,1,0))



correlation2 <-
  fullsetbaked 
 
M2 <- 
  cor(correlation2)
# png(file="corr.png", res=300, width=4500, height=4500)
# png(file="C:/Users/asbru/Documents/Emory/Forecasting and Predictive Analytics/Final/corr.png", res=300, width=4500, height=4500)
corrplot(M2, method = "shade", number.cex = 0.5, tl.cex = 0.6, title = "Narrowed Correlation", mar=c(0,0,1,0))


##Smaller Corerlation Matrix for Presentation. Include both Highly Positive and Highly Negative Correlations
# correlation3 <-
#   fullsetbaked %>% 
#   select(Total)


```

##Package Select: Ranger - randomForest - randomForestSRC Runtime Comparison

```{r}

# fullset.imputed <- rfImpute(SalePrice ~ .,data = fullsetbaked, iter = 6)


features <- setdiff(names(fullsetbaked), "SalePrice")
start.time = proc.time() 
model_ranger<- ranger(formula   = SalePrice ~ .,
    data      = fullsetbaked,
    num.trees = 1000,
    mtry      = floor(length(features) / 3)
)
proc.time() - start.time

start.time = proc.time() 
model_rfsrc <- rfsrc(SalePrice ~ ., data = as.data.frame(fullsetbaked), ntree=1000, samptype='swr')
proc.time() - start.time

start.time = proc.time() 
model_rf <- randomForest(formula = SalePrice ~ ., data = fullsetbaked)
proc.time() - start.time


print(model_ranger)
print(model_rfsrc)
print(model_rf)



# pred.rfsrc <- predict(model_rfsrc, fullsetbaked)
# pred.frsrc <- pred.rfsrc$predicted
# accuracy(pred.rfsrc, fullsetbaked$SalePrice)
# 
# pred.rf <- predict(model_rf, fullsetbaked)
# pred.fr <- as.vector(pred.rf$predicted)
# accuracy(pred.rf, fullsetbaked$SalePrice)
# 
# pred.ranger <- predict(model_ranger, fullsetbaked)
# pred.RF <- as.vector(pred.ranger$predicted)
# accuracy(pred.ranger, fullsetbaked$SalePrice)
# 
# plot(model_rf)
# plot(model_rfsrc)
# plot(model_ranger)
```


#Error rate comparison

```{r}
x_test <- testv2[setdiff(names(testv2), "SalePrice")]
y_test <- testv2$SalePrice

set.seed(1)
rf_oob_comp <- randomForest(
  formula = SalePrice ~ .,
  data    = trainv2,
  xtest   = x_test,
  ytest   = y_test,
  keep.forest = TRUE
)

oob <- sqrt(rf_oob_comp$mse)
validation <- sqrt(rf_oob_comp$test$mse)

error_df <- data.frame(oob,validation)

error_df <-
  error_df %>% 
  mutate(ntrees = 1:rf_oob_comp$ntree)

# write.csv(error_df, file = "C:/Users/asbru/Documents/Emory/Forecasting and Predictive Analytics/Final/errors.csv")

errorline <- 
  error_df %>% 
  pivot_longer(cols = c(oob,validation),names_to = "Metric", values_to = "RMSE") %>% 
  ggplot(aes(x = ntrees, y = RMSE, color = Metric)) +
  geom_line() +
  theme_wsj() +
  theme(axis.title=element_text(size=12),plot.title = element_text(size = 12)) +
  labs(x = "# of Trees", y = "RMSE") +
  labs(title = "Random Forest Performance")
errorline


which.min(rf_oob_comp$mse)
sqrt(rf_oob_comp$mse[which.min(rf_oob_comp$mse)])


which.min(rf_oob_comp$test$mse)
sqrt(rf_oob_comp$test$mse[which.min(rf_oob_comp$test$mse)])

print(rf_oob_comp)

```


##Generate Linear Model for Comparison against Optimal RF

```{r}
# lapply(trainv2, levels)
# trainv3 <-
# trainv2 %>% 
#   select(-Neighborhood,-Utilities)

model_linear <- lm(SalePrice ~ .,data = trainv2)
# summary(model_linear)

pred.lm <- predict(model_linear, testv2)
# pred.lm <- model_linear$
forecast::accuracy(pred.lm, testv2$SalePrice)
#######


set.seed(1)

rf_oob_comp2 <- randomForest(
  formula = SalePrice ~ .,
  data    = trainv2,
  xtest   = x_test,
  ytest   = y_test,
  keep.forest = TRUE,
  ntrees = 86
)

pred.rf3 <- predict(rf_oob_comp2, testv2)
# pred.lm <- model_linear$
forecast::accuracy(pred.rf3, testv2$SalePrice)
```

##Extract Examples for Presentation

```{r}

Testv3 <-
  testv2 %>% 
  mutate(lmpredict = predict(model_linear, testv2),
         rfpredict = predict(rf_oob_comp, testv2))

write.csv(Testv3, "C:/Users/asbru/Documents/Emory/Forecasting and Predictive Analytics/Final/predictions.csv")
head(Testv3)

```

##Linear Regression Results and RF Variable Improtance

```{r}
summary(model_linear) 

testimp <- 
  as.data.frame(importance(rf_oob_comp)) %>% 
  rownames_to_column() %>% 
  ggplot(aes(x = IncNodePurity, y = reorder(rowname,IncNodePurity))) +
  geom_col() +
  theme_wsj() +
  theme(axis.title=element_text(size=12),plot.title = element_text(size = 12)) +
  labs(x = "Node Purity", y = "Variable Name") +
  labs(title = "Random Forest Variable Importance")
  # theme(axis.title = element_text(), axis.title.x = element_blank()) + ylab('Variable Name')
testimp
```


